apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stackit-cert-manager-webhook.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "stackit-cert-manager-webhook.name" . }}
    chart: {{ include "stackit-cert-manager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "stackit-cert-manager-webhook.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "stackit-cert-manager-webhook.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "stackit-cert-manager-webhook.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port=8443
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            {{- if .Values.stackitSaAuthentication.enabled }}
            - name: STACKIT_SERVICE_ACCOUNT_KEY_PATH
              value: "{{ .Values.stackitSaAuthentication.mountPath}}/{{ .Values.stackitSaAuthentication.fileName}}"
            {{- end }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
            {{- if .Values.stackitSaAuthentication.enabled }}
            - name: stackit-sa-authentication
              mountPath: {{ .Values.stackitSaAuthentication.mountPath }}
              readOnly: true
            {{- end }}
            {{- if .Values.additionalVolumeMounts }}
{{ toYaml .Values.additionalVolumeMounts | indent 12 }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: certs
          secret:
            secretName: {{ include "stackit-cert-manager-webhook.servingCertificate" . }}
        {{- if .Values.stackitSaAuthentication.enabled }}
        - name: stackit-sa-authentication
          secret:
            secretName: {{ .Values.stackitSaAuthentication.secretName }}
        {{- end }}
        {{- if .Values.additionalVolumes }}
{{ toYaml .Values.additionalVolumes | indent 8 }}
        {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
